# Analysis of using open AI strict mode. 

OpenAI has a strict mode, see post at: https://cookbook.openai.com/examples/structured_outputs_intro, so we wanted to see how it interacts with deteriminsm. 

TL;DR Turns out the system is producing consistent json but just not the same json.

In [1]:
import pandas as pd
pd.options.display.max_columns = 250 #(default is 20)
pd.options.display.max_rows = 250 #(default is 60)
pd.options.display.max_colwidth = 250 #(default is 50)

# stability_eval.csv created by running `python ../../evaluate.py runs/`

df = pd.read_csv('stability_eval.csv')
display(df.sort_values(by='task'))

,Unnamed: 0,model,model_config,task,task_config,TACr,TARr,TACa,TARa,correct_count_per_run,correct_pct_per_run,num_questions,N,best_possible_count,best_possible_accuracy,worst_possible_count,worst_possible_accuracy,spread,bootstrap_counts,bootstrap_pcts,date
1,1,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",college_mathematics,"{'prompt_type': 'v2', 'shots': 'few'}",45,45.0%,47,47.0%,"[45, 52, 48, 45, 43]","['45.0%', '52.0%', '48.0%', '45.0%', '43.0%']",100,5,67,67.0%,30,30.0%,37.0%,"[42, 44, 44, 45, 46, 47, 47, 47, 51, 52]","['42.0%', '44.0%', '44.0%', '45.0%', '46.0%', '47.0%', '47.0%', '47.0%', '51.0%', '52.0%']",2025-03-01_16-53-09
2,2,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",high_school_european_history,"{'prompt_type': 'v2', 'shots': 'few'}",153,92.7%,153,92.7%,"[149, 147, 151, 150, 147]","['90.3%', '89.1%', '91.5%', '90.9%', '89.1%']",165,5,153,92.7%,142,86.1%,6.7%,"[146, 147, 148, 148, 149, 149, 149, 150, 150, 150]","['88.5%', '89.1%', '89.7%', '89.7%', '90.3%', '90.3%', '90.3%', '90.9%', '90.9%', '90.9%']",2025-03-02_08-48-33
3,3,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",logical_deduction,"{'prompt_type': 'v2', 'shots': 'few'}",223,89.2%,223,89.2%,"[229, 231, 232, 234, 230]","['91.6%', '92.4%', '92.8%', '93.6%', '92.0%']",250,5,244,97.6%,217,86.8%,10.8%,"[227, 229, 230, 230, 231, 232, 232, 232, 232, 235]","['90.8%', '91.6%', '92.0%', '92.0%', '92.4%', '92.8%', '92.8%', '92.8%', '92.8%', '94.0%']",2025-03-01_17-03-49
0,0,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'schema': None, 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': ...",navigate,"{'prompt_type': 'v2', 'shots': 'few'}",150,60.0%,150,60.0%,"[186, 187, 184, 183, 191]","['74.4%', '74.8%', '73.6%', '73.2%', '76.4%']",250,5,232,92.8%,132,52.8%,40.0%,"[180, 184, 185, 185, 186, 186, 188, 189, 191, 192]","['72.0%', '73.6%', '74.0%', '74.0%', '74.4%', '74.4%', '75.2%', '75.6%', '76.4%', '76.8%']",2025-03-01_10-58-34
4,4,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",professional_accounting,"{'prompt_type': 'v2', 'shots': 'few'}",180,63.8%,181,64.2%,"[206, 206, 213, 214, 215]","['73.0%', '73.0%', '75.5%', '75.9%', '76.2%']",282,5,249,88.3%,167,59.2%,29.1%,"[204, 206, 206, 207, 207, 207, 208, 212, 214, 214]","['72.3%', '73.0%', '73.0%', '73.4%', '73.4%', '73.4%', '73.8%', '75.2%', '75.9%', '75.9%']",2025-03-01_15-55-58
5,5,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",public_relations,"{'prompt_type': 'v2', 'shots': 'few'}",85,77.3%,85,77.3%,"[85, 82, 89, 83, 88]","['77.3%', '74.5%', '80.9%', '75.5%', '80.0%']",110,5,98,89.1%,75,68.2%,20.9%,"[80, 83, 84, 85, 86, 86, 86, 86, 88, 90]","['72.7%', '75.5%', '76.4%', '77.3%', '78.2%', '78.2%', '78.2%', '78.2%', '80.0%', '81.8%']",2025-03-02_11-20-08
6,6,gpt-4o_OAI,"{'temperature': 0.0, 'seed': 12, 'top_p_k': 1.0, 'system': 'Please answer the following question with the answer field only.', 'system_content': 'Please answer the following question with the answer field only.', 'answer_schema': {'name': 'answer...",ruin_names,"{'prompt_type': 'v2', 'shots': 'few'}",229,91.6%,229,91.6%,"[227, 226, 224, 228, 228]","['90.8%', '90.4%', '89.6%', '91.2%', '91.2%']",250,5,235,94.0%,215,86.0%,8.0%,"[225, 225, 225, 226, 227, 227, 228, 228, 228, 229]","['90.0%', '90.0%', '90.0%', '90.4%', '90.8%', '90.8%', '91.2%', '91.2%', '91.2%', '91.6%']",2025-03-02_07-34-04